"""Add TestSlot and slot_id to Booking

Revision ID: 4f728a59e899
Revises: f6656b2cbb3c
Create Date: 2026-09-28 12:48:08.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f728a59e899'
down_revision: Union[str, Sequence[str], None] = 'f6656b2cbb3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_booked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['diagnostic_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_slots_test_id'), 'test_slots', ['test_id'], unique=False)
    op.add_column('bookings', sa.Column('slot_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_bookings_slot_id'), 'bookings', ['slot_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'test_slots', ['slot_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_slot_id'), table_name='bookings')
    op.drop_column('bookings', 'slot_id')
    op.drop_index(op.f('ix_test_slots_test_id'), table_name='test_slots')
    op.drop_table('test_slots')
    # ### end Alembic commands ###
